nginx:
    build: nginx
    restart: always
    ports:
        - "80:80"
        - "443:443"
    links:
        - fpm
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
fpm:
    build: fpm
    restart: always
    expose:
        - "9000"
